### ISSUE TITLE
Paragraf should be removed?

### ISSUE THREAD

**Issue by vonDowntown** [enowars/enowars3-EnoTeams#5]
https://github.com/enowars/enowars3-EnoTeams/blob/0bc11af834361a7a7f11ef5e7c8130b1fb75d1db/app/templates/vms.html#L45

So as far as i am concerned you shouldn't need to do that for our ctf.

RFC: @DirectWeb 

Also if we do not remove that we need to change to ipv4

**Comment by nkowallik** [comment]
Can this be closed? Bridging the network is out of the plan, right?
